name: Deploy

# on:
#   push:
#     branches:
#       - main

on: [push]

jobs:
  # chrome-integration-test:
  #   runs-on: ubuntu-20.04

  #   strategy:
  #     matrix:
  #       node: ['14.x']

  #   steps:
  #     - name: Setup Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: npm install --only=prod

  #     - name: Execute tests
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: npm run dev:integration
  #         browser: chrome
  #         headless: true

  firefox-integration-test:
    runs-on: ubuntu-16.04

    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001

    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Execute tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev:integration
          browser: firefox
          headless: true

  # edge-integration-test:
  #   runs-on: macos-latest

  #   strategy:
  #     matrix:
  #       node: ['14.x']

  #   steps:
  #     - name: Setup Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: npm install --only=prod

  #     - name: Execute tests
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: npm run dev:integration
  #         browser: edge
  #         headless: true

  # deploy:
  #   - name: Setup Checkout
  #     uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Execute tests
  #     run: |
  #       npm run test:lint
  #       npm run test:unit

  #   - name: Deploy
  #     uses: amondnet/vercel-action@v20
  #     with:
  #       vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #       vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #       vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #       vercel-args: '--prod'
