name: Deploy

# on:
#   push:
#     branches:
#       - main

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Production

    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

        run: echo ${{ secrets.NODE_ENV }}

      - name: Execute initial tests
        run: |
          npm run test:lint
          npm run test:unit

      - name: Execute integration tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev:integration
          headless: true

      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
