name: Preview Deploy

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'support/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Execute linter test
        run: npm run test:lint

      - name: Execute unit tests
        run: npm run test:unit

      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
